import pandas as pd
import os

# Define the input and output file names
# Input: The full report generated by the Optimizer
# Output: The filtered table used by the final render script
input_file = r"C:\Users\vishn\Desktop\avanthik\bldr_op\non_uni_pos_lit_rndr\oth_bldr_als\nrfld_als\type_02\4096_180\bst_exp_cal_op\Optimization_Report.csv"
output_file = r"C:\Users\vishn\Desktop\avanthik\bldr_op\non_uni_pos_lit_rndr\oth_bldr_als\nrfld_als\type_02\4096_180\bst_exp_cal_op\Aggregated_EV_Report.csv"

# 1. Read the input CSV file
if os.path.exists(input_file):
    df_in = pd.read_csv(input_file)
    
    # 2. Filter the DataFrame to keep only aggregated rows
    # These rows contain the 'Man' tag within the 'Light_Setup' column 
    # and the 'Source_ID' set to 'AGGREGATE'
    df_agg = df_in[df_in['Source_ID'] == 'AGGREGATE'].copy()

    # 3. Select and reorder the required columns
    # We maintain the structure required by the final render script
    required_columns = [
        'Samples',
        'Configuration',
        'Light_Setup',
        'Aggregated_Mean_EV_Classical',
        'Aggregated_Mean_EV_GD'
    ]

    # Use list comprehension to ensure we only grab columns that actually exist
    df_out = df_agg[[c for c in required_columns if c in df_agg.columns]]

    # 4. Write the resulting DataFrame to a new CSV file
    df_out.to_csv(output_file, index=False)
    print(f"Successfully generated {output_file} with {len(df_out)} manual configurations.")
else:
    print(f"Error: Could not find {input_file}. Please run upd_opt_exp.py first.")